# Pinned dependency file lists from their original CMakeLists.
add_library(jpeg8 STATIC
 "${M3_VENDOR}/utils/jpeglib/jaricom.c"
 "${M3_VENDOR}/utils/jpeglib/jcapimin.c"
 "${M3_VENDOR}/utils/jpeglib/jcapistd.c"
 "${M3_VENDOR}/utils/jpeglib/jcarith.c"
 "${M3_VENDOR}/utils/jpeglib/jccoefct.c"
 "${M3_VENDOR}/utils/jpeglib/jccolor.c"
 "${M3_VENDOR}/utils/jpeglib/jcdctmgr.c"
 "${M3_VENDOR}/utils/jpeglib/jchuff.c"
 "${M3_VENDOR}/utils/jpeglib/jcinit.c"
 "${M3_VENDOR}/utils/jpeglib/jcmainct.c"
 "${M3_VENDOR}/utils/jpeglib/jcmarker.c"
 "${M3_VENDOR}/utils/jpeglib/jcmaster.c"
 "${M3_VENDOR}/utils/jpeglib/jcomapi.c"
 "${M3_VENDOR}/utils/jpeglib/jcparam.c"
 "${M3_VENDOR}/utils/jpeglib/jcprepct.c"
 "${M3_VENDOR}/utils/jpeglib/jcsample.c"
 "${M3_VENDOR}/utils/jpeglib/jctrans.c"
 "${M3_VENDOR}/utils/jpeglib/jdapimin.c"
 "${M3_VENDOR}/utils/jpeglib/jdapistd.c"
 "${M3_VENDOR}/utils/jpeglib/jdarith.c"
 "${M3_VENDOR}/utils/jpeglib/jdatadst.c"
 "${M3_VENDOR}/utils/jpeglib/jdatasrc.c"
 "${M3_VENDOR}/utils/jpeglib/jdcoefct.c"
 "${M3_VENDOR}/utils/jpeglib/jdcolor.c"
 "${M3_VENDOR}/utils/jpeglib/jddctmgr.c"
 "${M3_VENDOR}/utils/jpeglib/jdhuff.c"
 "${M3_VENDOR}/utils/jpeglib/jdinput.c"
 "${M3_VENDOR}/utils/jpeglib/jdmainct.c"
 "${M3_VENDOR}/utils/jpeglib/jdmarker.c"
 "${M3_VENDOR}/utils/jpeglib/jdmaster.c"
 "${M3_VENDOR}/utils/jpeglib/jdmerge.c"
 "${M3_VENDOR}/utils/jpeglib/jdpostct.c"
 "${M3_VENDOR}/utils/jpeglib/jdsample.c"
 "${M3_VENDOR}/utils/jpeglib/jdtrans.c"
 "${M3_VENDOR}/utils/jpeglib/jerror.c"
 "${M3_VENDOR}/utils/jpeglib/jfdctflt.c"
 "${M3_VENDOR}/utils/jpeglib/jfdctfst.c"
 "${M3_VENDOR}/utils/jpeglib/jfdctint.c"
 "${M3_VENDOR}/utils/jpeglib/jidctflt.c"
 "${M3_VENDOR}/utils/jpeglib/jidctfst.c"
 "${M3_VENDOR}/utils/jpeglib/jidctint.c"
 "${M3_VENDOR}/utils/jpeglib/jmemmgr.c"
 "${M3_VENDOR}/utils/jpeglib/jmemnobs.c"
 "${M3_VENDOR}/utils/jpeglib/jquant1.c"
 "${M3_VENDOR}/utils/jpeglib/jquant2.c"
 "${M3_VENDOR}/utils/jpeglib/jutils.c"
)
target_include_directories(jpeg8 PRIVATE "${SOURCE_ROOT}/public/jpeglib")
target_compile_definitions(jpeg8 PRIVATE STRICT)
add_library(png15 STATIC
 "${M3_VENDOR}/thirdparty/libpng-1.5.30/png.c"
 "${M3_VENDOR}/thirdparty/libpng-1.5.30/pngerror.c"
 "${M3_VENDOR}/thirdparty/libpng-1.5.30/pngget.c"
 "${M3_VENDOR}/thirdparty/libpng-1.5.30/pngmem.c"
 "${M3_VENDOR}/thirdparty/libpng-1.5.30/pngpread.c"
 "${M3_VENDOR}/thirdparty/libpng-1.5.30/pngread.c"
 "${M3_VENDOR}/thirdparty/libpng-1.5.30/pngrio.c"
 "${M3_VENDOR}/thirdparty/libpng-1.5.30/pngrtran.c"
 "${M3_VENDOR}/thirdparty/libpng-1.5.30/pngrutil.c"
 "${M3_VENDOR}/thirdparty/libpng-1.5.30/pngset.c"
 "${M3_VENDOR}/thirdparty/libpng-1.5.30/pngtrans.c"
 "${M3_VENDOR}/thirdparty/libpng-1.5.30/pngwio.c"
 "${M3_VENDOR}/thirdparty/libpng-1.5.30/pngwrite.c"
 "${M3_VENDOR}/thirdparty/libpng-1.5.30/pngwtran.c"
 "${M3_VENDOR}/thirdparty/libpng-1.5.30/pngwutil.c"
)
target_include_directories(png15 PRIVATE "${M3_VENDOR}/thirdparty/libpng-1.5.30")
target_link_libraries(png15 PRIVATE z)
target_link_libraries(server PRIVATE png15 jpeg8 z)
