# M4 builds the original SDL/TOGL and VGUI client paths from local VPC.
set(CMAKE_OBJCXX_STANDARD 11)

target_compile_definitions(source_platform INTERFACE USE_SDL)
get_target_property(SOURCE_SDL_INCLUDES SDL2::SDL2 INTERFACE_INCLUDE_DIRECTORIES)
target_include_directories(source_platform INTERFACE ${SOURCE_SDL_INCLUDES})
# The Intel-only 10.8 malloc instruction hook cannot apply to an ARM GPU/process.
list(FILTER VPC_togl_FILES EXCLUDE REGEX "/(intelglmallocworkaround\\.cpp|mach_override\\.c)$")
set(VPC_togl_FILES "${METAL_ROOT}/source_math.cpp" "${METAL_ROOT}/native_resources.mm" "${METAL_ROOT}/native_shaders.mm" "${METAL_ROOT}/source_device.mm" "${PORT_ROOT}/client/native_window_ios.mm" "${PORT_ROOT}/render/diagnostics_ios.mm")
m3_library(togl SHARED)
target_include_directories(togl PRIVATE "${METAL_ROOT}")
target_compile_definitions(togl PRIVATE TOGL_DLL_EXPORT)
target_compile_options(togl PRIVATE "$<$<COMPILE_LANGUAGE:OBJCXX>:-fobjc-arc>")
set_target_properties(togl PROPERTIES OUTPUT_NAME source_metal OBJCXX_STANDARD 17)
target_link_libraries(togl PRIVATE m6_mojoshader tier2 "-framework Metal" "-framework QuartzCore" "-framework Foundation" "-framework UIKit")
set(SOURCE_GRAPHICS_FRAMEWORK "-framework Metal")
target_sources(appframework PRIVATE "${PORT_ROOT}/client/native_display_ios.cpp")
target_link_libraries(appframework PRIVATE togl "-framework UIKit" ${SOURCE_GRAPHICS_FRAMEWORK})
foreach(tgt inputsystem vgui2 vguimatsurface launcher)
  m3_library(${tgt} SHARED)
  target_link_libraries(${tgt} PRIVATE tier2 tier3 steam_api  iconv)
endforeach()
target_compile_definitions(inputsystem PRIVATE NO_STRING_T PROTECTED_THINGS_ENABLE)
target_link_libraries(inputsystem PRIVATE  )
target_compile_definitions(vgui2 PRIVATE DONT_PROTECT_FILEIO_FUNCTIONS)
target_include_directories(vgui2 PRIVATE "${SOURCE_ROOT}/thirdparty")
m3_library(vgui_surfacelib STATIC)
target_link_libraries(vgui_surfacelib PRIVATE tier2  "-framework CoreGraphics" "-framework CoreText")
target_compile_definitions(vguimatsurface PRIVATE VGUIMATSURFACE_DLL_EXPORT GAMEUI_EXPORTS BENCHMARK DONT_PROTECT_FILEIO_FUNCTIONS PROTECTED_THINGS_ENABLE)
target_include_directories(vguimatsurface PRIVATE "${SOURCE_ROOT}/vgui2/src")
target_link_libraries(vguimatsurface PRIVATE vgui_surfacelib bitmap vtf vgui_controls "-framework CoreText" "-framework CoreGraphics")
target_link_libraries(vgui2 PRIVATE vgui_surfacelib bitmap vtf vgui_controls)
target_compile_definitions(launcher PRIVATE LAUNCHERONLY NO_STEAM)
target_link_libraries(launcher PRIVATE appframework togl "-framework UIKit"  ${SOURCE_GRAPHICS_FRAMEWORK} )
m3_library(videocfg STATIC)
target_include_directories(videocfg PRIVATE "${SOURCE_ROOT}/public/videocfg")
target_link_libraries(videocfg PRIVATE tier2)
m3_library(shaderapidx9 SHARED)
target_compile_definitions(shaderapidx9 PRIVATE SHADERAPIDX9 SHADER_DLL_EXPORT PROTECTED_THINGS_ENABLE SOURCE_MATERIALSYSTEM_SPLIT)
target_include_directories(shaderapidx9 PRIVATE "${SOURCE_ROOT}/materialsystem")
target_link_libraries(shaderapidx9 PRIVATE bitmap vtf videocfg tier2 togl bz2 ${SOURCE_GRAPHICS_FRAMEWORK} )
set(VPC_shaderlib_dynamic_FILES ${VPC_shaderlib_FILES})
m3_library(shaderlib_dynamic STATIC)
target_include_directories(shaderlib_dynamic PRIVATE "${SOURCE_ROOT}/materialsystem")
target_compile_definitions(shaderlib_dynamic PRIVATE FAST_MATERIALVAR_ACCESS SOURCE_MATERIALSYSTEM_SPLIT)
foreach(tgt stdshader_dx9 stdshader_dbg)
  m3_library(${tgt} SHARED)
  target_compile_definitions(${tgt} PRIVATE STDSHADER_DX9_DLL_EXPORT FAST_MATERIALVAR_ACCESS SOURCE_MATERIALSYSTEM_SPLIT)
  target_include_directories(${tgt} PRIVATE "${SOURCE_ROOT}/materialsystem" "${SOURCE_ROOT}/materialsystem/stdshaders/fxctmp9" "${SOURCE_ROOT}/materialsystem/stdshaders/vshtmp9")
  target_link_libraries(${tgt} PRIVATE shaderlib_dynamic tier2)
endforeach()
foreach(tgt matsys_controls matchmakingbase)
  m3_library(${tgt} STATIC)
  target_link_libraries(${tgt} PRIVATE tier2 tier3 vgui_controls)
endforeach()
m3_library(matchmaking SHARED)
target_compile_definitions(matchmaking PRIVATE MATCHMAKING_DLL NO_STEAM NO_STEAM_GAMECOORDINATOR NO_STRING_T VECTOR PROTECTED_THINGS_ENABLE)
target_compile_definitions(matchmakingbase PRIVATE NO_STEAM NO_STEAM_GAMECOORDINATOR NO_STRING_T VECTOR PROTECTED_THINGS_ENABLE)
foreach(tgt matchmaking matchmakingbase)
  target_include_directories(${tgt} PRIVATE "${SOURCE_ROOT}/matchmaking" "${SOURCE_ROOT}/game/shared" "${SOURCE_ROOT}/gcsdk/steamextra" "${SOURCE_ROOT}/common/xlast_csgo")
  target_link_libraries(${tgt} PRIVATE source_messages steam_api gcsdk_game)
endforeach()
target_link_libraries(matchmaking PRIVATE matchmakingbase)
m3_library(client SHARED)
target_compile_definitions(client PRIVATE CLIENT_DLL NO_STRING_T VECTOR CSTRIKE_CLIENT_DLL CSTRIKE_DLL GAMEUI_EMBEDDED GAMEUI_EXPORTS USE_ECONOMY_FEATURES PROTOBUF NO_STEAM_GAMECOORDINATOR NO_STEAM PROTECTED_THINGS_ENABLE)
target_include_directories(client PRIVATE "${SOURCE_ROOT}/game/client" "${SOURCE_ROOT}/game/client/game_controls" "${SOURCE_ROOT}/game/shared" "${SOURCE_ROOT}/game/shared/cstrike15" "${SOURCE_ROOT}/game/shared/cstrike15/control" "${SOURCE_ROOT}/game/client/cstrike15" "${SOURCE_ROOT}/game/client/cstrike15/control" "${SOURCE_ROOT}/game/client/cstrike15/VGUI" "${SOURCE_ROOT}/game/client/cstrike15/gameui" "${SOURCE_ROOT}/game/shared/econ" "${SOURCE_ROOT}/gcsdk/steamextra" "${SOURCE_ROOT}/utils/common" "${M3_VENDOR}/thirdparty/libpng-1.5.30")
target_link_libraries(client PRIVATE bitmap bonesetup choreoobjects dmxloader particles responserules tier2 tier3 source_messages steam_api vgui_controls matsys_controls kv3lib gcsdk_game png15 jpeg8 z)
add_dependencies(client source_messages)
target_link_libraries(engine PRIVATE togl vgui_controls videocfg)

foreach(tgt togl appframework inputsystem vgui2 vguimatsurface engine launcher)
 target_link_libraries(${tgt} PRIVATE SDL2::SDL2)
endforeach()

add_custom_command(OUTPUT "${CMAKE_BINARY_DIR}/generated/vscript_client_nut.h"
 COMMAND "${Python3_EXECUTABLE}" "/Users/shupokato/Documents/eng/macos-arm64/cmake/../scripts/embed_script.py"
 "${SOURCE_ROOT}/game/client/vscript_client.nut" "${CMAKE_BINARY_DIR}/generated/vscript_client_nut.h" "g_Script_vscript_client"
 DEPENDS "${SOURCE_ROOT}/game/client/vscript_client.nut" "/Users/shupokato/Documents/eng/macos-arm64/cmake/../scripts/embed_script.py" VERBATIM)
target_sources(client PRIVATE "${CMAKE_BINARY_DIR}/generated/vscript_client_nut.h")

m3_library(soundsystem_lowlevel STATIC)
target_link_libraries(soundsystem_lowlevel PRIVATE tier2 SDL2::SDL2)
target_link_libraries(vguimatsurface PRIVATE dmxloader)
target_link_libraries(engine PRIVATE matsys_controls soundsystem_lowlevel jpeg8  "-framework AudioToolbox"  "-framework OpenAL")
# M4 retains the original non-HRTF audio path; 2019 Phonon API restoration is M5.
foreach(src IN LISTS VPC_engine_FILES)
 if(src MATCHES "/audio/private/")
  set_property(SOURCE "${src}" APPEND PROPERTY COMPILE_DEFINITIONS SOURCE_NO_STEAMAUDIO)
 endif()
endforeach()

foreach(tgt mathlib_extended raytrace resourcefile meshutils)
 m3_library(${tgt} STATIC)
 target_link_libraries(${tgt} PRIVATE tier2)
endforeach()
target_include_directories(mathlib_extended PRIVATE "${SOURCE_ROOT}/public/mathlib")
target_compile_definitions(mathlib_extended PRIVATE MATHLIB_EXTENDED_LIB SOURCE1)
target_include_directories(raytrace PRIVATE "${SOURCE_ROOT}/utils/common")
target_sources(client PRIVATE "/Users/shupokato/Documents/eng/macos-arm64/cmake/../vendor/m4/emit_json_string.cpp")
target_link_libraries(client PRIVATE mathlib_extended raytrace resourcefile meshutils vtf videocfg  "-framework CoreFoundation")

target_include_directories(meshutils PRIVATE "${SOURCE_ROOT}/public/meshutils")

target_sources(client PRIVATE "/Users/shupokato/Documents/eng/macos-arm64/cmake/../probes/client_diagnostics.cpp")
if(BUILD_M6)
  target_sources(client PRIVATE "/Users/shupokato/Documents/eng/macos-arm64/cmake/../probes/m6_particle_render.cpp")
endif()
target_sources(client PRIVATE "/Users/shupokato/Documents/eng/macos-arm64/cmake/../probes/font_diagnostics.cpp")
target_sources(server PRIVATE "/Users/shupokato/Documents/eng/macos-arm64/cmake/../probes/m4_server_diagnostics.cpp")

m3_library(localize SHARED)
target_link_libraries(localize PRIVATE tier2 steam_api vgui_controls iconv)
