# One process-wide owner for upstream V8 and GLib/Pango global registries.
add_library(v8 SHARED "${PORT_ROOT}/client/providers.cpp")
set(V8_LIBS)
foreach(name v8_snapshot v8_base_without_compiler v8_compiler v8_initializers v8_libplatform v8_libbase v8_zlib icui18n icuucx icudata)
 add_library(ios_${name} STATIC IMPORTED)
 set_target_properties(ios_${name} PROPERTIES IMPORTED_LOCATION "${I1_CACHE}/node/out/Release-iphoneos/lib${name}.a")
 list(APPEND V8_LIBS ios_${name})
endforeach()
target_link_libraries(v8 PRIVATE "$<LINK_LIBRARY:WHOLE_ARCHIVE,${V8_LIBS}>" "-framework Foundation")
foreach(name v8_libbase v8_libplatform)
 add_library(${name} INTERFACE)
 target_link_libraries(${name} INTERFACE v8)
endforeach()
add_library(text_provider SHARED "${PORT_ROOT}/client/providers.cpp")
set(TEXT_LIBS)
foreach(name pangoft2-1.0 pangocairo-1.0 pango-1.0 cairo-gobject cairo fontconfig freetype harfbuzz fribidi pixman-1 gio-2.0 gobject-2.0 gmodule-2.0 glib-2.0 intl ffi pcre2-8)
 string(REPLACE "." "_" id "${name}")
 add_library(text_${id} STATIC IMPORTED)
 set_target_properties(text_${id} PROPERTIES IMPORTED_LOCATION "${I4_CACHE}/deps/lib/lib${name}.a")
 list(APPEND TEXT_LIBS text_${id})
endforeach()
target_link_libraries(text_provider PRIVATE "$<LINK_LIBRARY:WHOLE_ARCHIVE,${TEXT_LIBS}>" "-framework CoreFoundation" "-framework Foundation" "-framework Security" iconv z expat resolv)
target_include_directories(text_provider INTERFACE "${I4_CACHE}/deps/include" "${I4_CACHE}/deps/include/glib-2.0" "${I4_CACHE}/deps/lib/glib-2.0/include" "${I4_CACHE}/deps/include/pango-1.0" "${I4_CACHE}/deps/include/harfbuzz" "${I4_CACHE}/deps/include/freetype2" "${I4_CACHE}/deps/include/cairo" "${I4_CACHE}/deps/include/pixman-1")
add_library(ios_video INTERFACE)
foreach(name avformat avcodec swscale swresample avutil)
 add_library(ios_${name} STATIC IMPORTED)
 set_target_properties(ios_${name} PROPERTIES IMPORTED_LOCATION "${I4_CACHE}/deps/lib/lib${name}.a")
 target_link_libraries(ios_video INTERFACE ios_${name})
endforeach()
target_include_directories(ios_video INTERFACE "${I4_CACHE}/deps/include")
target_link_libraries(ios_video INTERFACE z bz2 iconv "-framework CoreFoundation")
