"VideoPreset"
{
	"cpu_level" { "value" "0" "auto" "0" }
	"gpu_level" { "value" "0" "auto" "0" }
	"mat_antialias" { "value" "0" "auto" "0" }
	"mat_aaquality" { "value" "0" "auto" "0" }
	"mat_forceaniso" { "value" "2" "auto" "0" }
	"mat_vsync" { "value" "0" "auto" "0" }
	"mat_triplebuffered" { "value" "0" "auto" "0" }
	"mat_grain_scale_override" { "value" "-1.0" "auto" "0" }
	"gpu_mem_level" { "value" "1" "auto" "0" }
	"mat_queue_mode" { "value" "0" "auto" "0" }
	"csm_quality_level" { "value" "1" "auto" "0" }
	"mat_software_aa_strength" { "value" "0" "auto" "0" }
	"mat_motion_blur_enabled" { "value" "0" "auto" "0" }
}
